# Generated by Django 2.1.3 on 2022-03-31 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_item_sample_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sample_1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='サンプル項目1_文字列'),
        ),
    ]
