# Generated by Django 2.1.3 on 2022-03-31 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_item_sample_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='sample_1',
        ),
    ]
